<?php

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function select2_widget_field_widget_options_select_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['cardinality'] == 1) {
    // If limited to a single value, do not use Select2.
    return $element;
  }

  $element += array(
    '#after_build' => array('select2_widget_field_widget_after_build'),
    '#cardinality' => $context['field']['cardinality'],
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'select2_widget') . '/css/select2.css',
        drupal_get_path('module', 'select2_widget') . '/css/select2-widget.css',
      ),
      'js' => array(
        drupal_get_path('module', 'select2_widget') . '/js/select2.js',
        drupal_get_path('module', 'select2_widget') . '/js/select2-widget.js',
      ),
    ),
  );

  return $element;
}

function select2_widget_field_widget_after_build($element, &$form_state) {
  $setting = drupal_static('__FUNCTION__', array());

  $setting[] = array(
    'selector' => '#' . $element['#id'],
    'cardinality' => $element['#cardinality'],
  );

  drupal_add_js(array('select2_widget' => $setting), 'setting');

  return $element;
}
